# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.gd <- function(x, y, b, stepsize, maxit, tolerance) {
    .Call(`_gradient_gd`, x, y, b, stepsize, maxit, tolerance)
}

.sd <- function(x, y, b, maxit, tolerance) {
    .Call(`_gradient_sd`, x, y, b, maxit, tolerance)
}

